### ISSUE TITLE
Automate backend env deployment

### ISSUE THREAD

**Issue by tirthajyoti-ghosh** [get-amigo/Amigo-Backend#6]
Using GH actions:

- deploy to `prod` -> push to `master` branch
- deploy to `staging` -> push to `staging` branch
- deploy to `develop` -> push to `develop` branch

**Comment by vikhyat187** [comment]
Hey @tirthajyoti-ghosh I will try working on this, will let you know if I'm not able to work on it, let me try setting up things once on sunday and get back

**Comment by tirthajyoti-ghosh** [comment]
Hey @vikhyat187 appreciate your interest working on this issue. I have draft changes locally saved that I haven't yet committed. Got busy with work in the past few days. I'll take care of it in a few days.

**Comment by vikhyat187** [comment]
Sure no problem.
Thanks for informing @tirthajyoti-ghosh

**Comment by tirthajyoti-ghosh** [comment]
Done
